---
- name: Clone dotfiles
  become: no
  ansible.builtin.git:
    repo: '{{ dotfiles_repo }}'
    dest: '{{ dotfiles_repo_dest }}'
    ssh_opts: '-o StrictHostKeyChecking=accept-new'
    update: yes
    recursive: yes
    track_submodules: yes
    force: '{{ discard_changes }}'

- name: Link dotfiles
  ansible.builtin.include_tasks: link.yml
  loop: "{{ dotfiles | subelements('files') }}"
