---
- name: Converge
  hosts: all
  #become: true

  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_facts.os_family == 'Debian'

  roles:
    - role: geerlingguy.git
    - role: geerlingguy.dotfiles
      dotfiles_repo: https://github.com/egdoc/dotfiles.git
      dotfiles_files:
        - bash_profile
        - bashrc
      dotfiles_add_dot_prefix: true
